# Main Config - CustomCrafting v0.0.9.141
# -
# PlaceholderAPI:
# Identifier: customcrafting
# Placeholders:
#   - amount_crafted -> returns the number of crafted custom recipes!
# -
# -
# Debug should be disabled! That are a lot of Messages!
debug: false
# Do NOT use it until you know what you are doing!
experimental_features: false

#The language you want use. The context: <language>_<country>
#If you have any language file you want to be added to this plugin, then feel free to contact me.
language: en_US

creator:
  reset_after_save: true


#This can be set to false if you have conflicting plugins that also use the alias /cc
commands:
  cc: true
  alias:
    - "cc"

databank:
  enabled: false
  type: MYSQL
  host: ""
  port: 3306
  database: ""
  username: ""
  password: ""

workbench:
  enable: true
  reset: true
  # Sound after successful crafting!
  craft_sound:
    enable: false
    sound: "block.lava.extinguish"

  commands:
    #The commands that are called after successful craft!
    successful_craft: []
    #The commands that are called when the recipe was denied! Caution! It could cause spam!
    denied_craft: []

data:
  auto_save:
    # Interval in minutes
    interval: 30
    message: true

recipes:
  lockdown: false
  vanilla_knowledgebook: true
  pretty_printing: true
  disabled_recipes: []

knowledgebook:
  reset: true