name: CustomCrafting
main: me.wolfyscript.customcrafting.CustomCrafting
version: ${project.version}
api-version: "1.16"

depend:
  - WolfyUtilities
softdepend:
  - PlaceholderAPI
description: Create your own custom recipes for workbenches and furnaces. Disable Vanilla recipes and more.