name: CustomCrafting
authors: [ WolfyScript ]
main: me.wolfyscript.customcrafting.CustomCrafting
version: ${project.version}
api-version: "1.14"
depend: [ WolfyUtilities ]
softdepend: [ PlaceholderAPI, MythicMobs, Oraxen, ItemsAdder ]
description: Create your own custom recipes for workbenches and furnaces. Disable Vanilla recipes and more.