# Crafting Recipe Config

permissions: true
advanced_workbench: false
exactItemMeta: false
priority: NORMAL
group: ''
shapeless: true
shape:
  - '   '
  - ' E '
  - ' H '
result:
  item_key: customcrafting:knowledge_book
  custom_amount: 0
ingredients:
  E:
    var0:
      item:
        v: 1968
        type: BOOK
  H:
    var0:
      item:
        v: 1968
        type: CRAFTING_TABLE