# Crafting Recipe Config

permissions: false
advanced_workbench: false
exactItemMeta: false
priority: "NORMAL"
group: ''
shapeless: false
shape:
  - ' B '
  - ' E '
  - ' H '
result:
  item_key: customcrafting:workbench
ingredients:
  B:
    var0:
      item:
        v: 1631
        type: GOLD_INGOT
  E:
    var0:
      item:
        v: 1631
        type: CRAFTING_TABLE
  H:
    var0:
      item:
        v: 1631
        type: REDSTONE