#The cost of this recipe
repair_cost: 0
#Blocks repairing! Only if input_right is blank!
block_repairing: false
#Blocks the renaming of the item!
block_rename: false
#Blocks the enchanting of the item. Only useful if input_right if left blank!
block_enchant: false

#The order in which the recipes are checked!
priority: NORMAL

mode:
  #DURABILITY (increases or decreases the durability of input_left and set it as the result)
  durability: 1

  #RESULT (Will always return this item! No matter which you put in the anvil!)
  result: #CustomItem

#Each of the inputs can be left blank! So that means you can have both set, or you have either input_left or input_right set!
#input_left=true, input_right=false:
#   - The recipe is allowed when input_left contains the item(slot 0)!
#
#input_left=false, input_right=true:
#   - The recipe is allowed if input_right contains the item(slot 1)!
#   - The items in slot 0 are ignored!
#
#input_left=true, input_right=true:
#   - The recipe is allowed if the input_left contains the item(slot 0) and input_right contains the item(slot 1)!

#Supports multiple choices of items, so you don't need to create a recipe for each tool etc.!
input_left:
  var0:
    item: #CustomItem
    #Ignores the consume options set to the item! Yes they will also apply to anvil recipes!
    ignore_consume: false
  var1:
    item:
    ignore_consume: false
  #etc.

#Also supports multiple choices!
input_right:
  var0:
    item:
    ignore_consume: false
  #same as for input_left