blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/qGhDTSr
    about: If you have minor issues or questions in general about the plugin, feel free to join the Discord server!