name: CustomCrafting
main: me.wolfyscript.customcrafting.CustomCrafting
version: 1.4.4.1
api-version: 1.13

depend:
  - WolfyUtilities
softdepend:
  - PlaceholderAPI
description: Create your own custom recipes for workbenches and furnaces. Disable Vanilla recipes and more.

commands:
  customcrafting:
    usage: /customcrafting <label>
    description: Main command
  cc:
    usage: /cc <label>
    description: Main Command alternativ
  recipes:
    usage: /recipes <label>
    description: Command to quick edit, delete, toggle recipes