item:
  v: 1631
  type: COBBLESTONE
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '&7Compressed Cobblestone'
    lore:
      - '&39x Cobblestone'
    enchants:
      DURABILITY: 1
    ItemFlags:
      - HIDE_ENCHANTS