# Crafting Recipe Config

permissions: false
advanced_workbench: true
override: []
extend: ''
group: ''
shapeless: false
shape:
  - ABC
  - DEF
  - GHI
result:
  item_key: customcrafting:furnace
ingredients:
  A:
    var0:
      item_key: customcrafting:compressed_cobblestone
  B:
    var0:
      item_key: customcrafting:compressed_cobblestone
  C:
    var0:
      item_key: customcrafting:compressed_cobblestone
  D:
    var0:
      item_key: customcrafting:compressed_cobblestone
  E:
    var0:
      item:
        v: 1631
        type: FURNACE
  F:
    var0:
      item_key: customcrafting:compressed_cobblestone
  G:
    var0:
      item_key: customcrafting:compressed_cobblestone
  H:
    var0:
      item:
        v: 1631
        type: LAVA_BUCKET
  I:
    var0:
      item_key: customcrafting:compressed_cobblestone