item:
  v: 1631
  type: FURNACE
  meta:
    ==: ItemMeta
    meta-type: TILE_ENTITY
    display-name: '&6Advanced Furnace&:&c&c&_&f&u&r&n&a&c&e'
    lore:
      - '&7Furnace for advanced smelting'
    enchants:
      FIRE_ASPECT: 9
    ItemFlags:
      - HIDE_ENCHANTS
    blockMaterial: FURNACE