# Crafting Recipe Config

permissions: true
advanced_workbench: false
group: ''
shapeless: false
shape:
  - RIR
  - IFI
  - RIR
ingredients:
  F:
    var1:
      item:
        v: 1631
        type: FURNACE
        amount: 1
      data: []
  I:
    var1:
      item:
        v: 1631
        type: IRON_INGOT
        amount: 1
      data: []
  R:
    var1:
      item:
        v: 1631
        type: REDSTONE
        amount: 1
      data: []
result:
  v: 1631
  type: FURNACE
  amount: 1
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '&6Advanced Furnace&:&c&c&_&f&u&r&n&a&c&e'
    lore:
      - '&7Furnace for advanced smelting'
    enchants:
      FIRE_ASPECT: 9
    ItemFlags:
      - HIDE_ENCHANTS