item:
  v: 1631
  type: CRAFTING_TABLE
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '&6Advanced Workbench'
    lore:
      - '&7Workbench for advanced crafting'
      - '&c&c&_&w&o&r&k&b&e&n&c&h'
    enchants:
      FIRE_ASPECT: 9
    ItemFlags:
      - HIDE_ENCHANTS