item:
  v: 1631
  type: CRAFTING_TABLE
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '&6Advanced Workbench'
    lore:
      - 'Workbench for advanced crafting'
      - 'The Name and Lore will be overridden!'
      - 'Only the Enchantments and ItemFlags will stay!'
      - 'Name and Lore can be configured in the language file!'
    enchants:
      FIRE_ASPECT: 9
    ItemFlags:
      - HIDE_ENCHANTS