fuel:
  burntime: 0
  allowed_blocks: []
durability_cost: 0
item:
  v: 1631
  type: CRAFTING_TABLE
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: $crafting.workbench.name$
    lore:
      - '[WU!]$crafting.workbench.lore$'
      - '&c&c&_&w&o&r&k&b&e&n&c&h'
    enchants:
      FIRE_ASPECT: 0
    ItemFlags:
      - HIDE_ENCHANTS