# Main Config - CustomCrafting v0.0.0.1

debugging: false
language: en_US

spooky_workbench:
  enable: false
  jack_o_lantern: false

workbench:
  # Sound after successful crafting! Set to "none" to disable it
  craft_sound: "block.lava.extinguish"

data:
  auto_save:
    # Interval in minutes
    interval: 30
recipes:
  reload_after_save: false
  disable_vanilla_recipes: []