# Main Config - CustomCrafting v0.0.0.1

debugging: true
auto_Update: true
language: en_US

spooky_workbench:
  enable: false
  jack_o_lantern: false

workbench:
  craft_sound: "block.lava.extinguish"

data:
  auto_save:
    interval: 30
recipes:
  reload_after_save: false