# Main Config - CustomCrafting v0.0.9.141
#
#PlaceholderAPI:
# Identifier: customcrafting
# Placeholders:
#   - amount_crafted -> returns the number of crafted custom recipes!
#

#This should be disabled! That are a lot of Messages!
debug: false

#The language you want use. The context: <language>_<country>
#If you have any language file you want to be added to this plugin, then feel free to contact me.
language: en_US

workbench:
  enable: true

  # Sound after successful crafting!
  craft_sound:
    enable: false
    sound: "block.lava.extinguish"

  commands:
    #The commands that are called after successful craft!
    successful_craft: []
    #The commands that are called when the recipe was denied! Caution! It could cause spam!
    denied_craft: []

data:
  auto_save:
    # Interval in minutes
    interval: 30

recipes:
  disabled_recipes: []