name: CustomCrafting
main: me.wolfyscript.customcrafting.CustomCrafting
version: 0.0.10.0
api-version: 1.13

depend:
  - WolfyUtilities
softdepend:
  - PlaceholderAPI
description: Create your own custom recipes for workbenches and furnaces. Disable Vanilla recipes and more.

commands:
  customcrafting:
    usage: /customcrafting <label>
    description: Main command
  cc: