name: CustomCrafting
main: me.wolfyscript.customcrafting.CustomCrafting
version: 0.0.1.0
api-version: 1.13

depend:
  - WolfyUtilities
description: Plugin to create your own crafting recipes

commands:
  cc:
    usage: /cc
    description: Something