# Language: en_US
author: "WolfyScript"
version: "1.0.0"
info:
  - "YouTube:"
  - "   https://www.youtube.com/channel/UCTlqRLm4PxZuAI4nVN4X74g"
######################################################################
msg:
  auto_save:
    start:    "   Auto save data   "
    complete: " Auto save complete "
  startup:
    playerstats: "Loading Player Stats"
    inventories: "Initiating Inventory GUIs"
    placeholder: "Registering PlaceHolder"
    recipes:
      title:   "________[Loading Recipes/Items]________"
      items:   "---------[ITEMS]---------"
      recipes: "--------[RECIPES]--------"
  gui:
    item_creator:
      save:
        input:
          line1: "&3Type in the name of the folder and item"
          line2: "&6e.g. example your_item"
        success: "&aItem saved to:"
      display_name: "&2Type in the name! Use &6& &2for formatting codes!"
      enchant:
        add: "&2Type in the enchantment and level! &6unbreaking 5"
        remove: "&2Type in the enchantment! &6unbreaking"
        invalid_lvl: "&cInvalid level! It's not a number!"
        invalid_enchant: "&cInvalid Enchantment! &4%ENCHANT%&c does not exist!"
        no_lvl: "&cNo level set!"
      lore:
        add: "&2Type in the lore! Use &6& &2for formatting codes!"
        remove: "&2Type in the line of the lore you want to remove!"
        no_number: "&cError getting the line! Is it a number? It should be!"
        error: "&cError the line &4%NUM%&c does not exist!"
        success: "&aRemoved Lore in line &6%NUM%"
      potion:
        add: "&2Type in the Potion name, level, time in ticks! e.g. &6speed 5 1200"
        remove: "&2Type in the Potion name you want to remove!"
        error_number: "&cError parsing Numbers! &4<name> <duration> <level> [<ambient> <particles>]"
        wrong_args: "&cWrong arguments or invalid name! &4<name> <duration> <level> [<ambient> <particles>]"
        success: "&aAdded Potion Effect &6%TYPE%,%DUR%,%AMP%,%AMB%,%PAR%"
        invalid_name: "&cInvalid name! &4%NAME%&c does not exist!"
      variant:
      attribute:
        amount:
          input: "§3Type in the amount you want! For example§6 0.4"
          error: "&cError parsing number! Is it a number? It should be!"
        name:
          input: "§3Type in the name!"
        uuid:
          input: "§3Type in the uuid for the attribute! Must be a valid UUID!"
          error:
            line1: "&cInvalid UUID: &4%UUID%"
            line2: "&cType in a valid UUID!"
      skull_owner:
        input: "§3Type in the Player Name!"
    item_editor:
      input: "&3Type in the folder and name of the item! &6example your_item"
      error: "&cThis item does not exist or is not loaded!"
      item_gui_title: "       §cID ITEM     §3ORIGINAL ITEM"
      item_applied: "&aItem successfully applied to recipe!"
      item_editable: "&aThis item can now be edited!"
      no_name: "&cYou need to type in the item name!"
    recipe_creator:
      extends: "&3type the namespace and key from the recipe!"
      furnace:
        xp: "&3Type in the amount of experience. e.g. 0.5"
        cooking_time: "&3Type in the cooking time in ticks. e.g. 20"
      save:
        input: "&3Type in the name of the folder and item! &6e.g. example your_recipe"
        empty: "&cCannot save a empty recipe! Check the Result and the Source/ingredients"
        success: "&aRecipe successfully saved to:"
      error_loading: "&cError occurred while loading recipe &4%REC%"
      valid_number: "&cType in a valid number!"
    recipe_editor:
      input: "&3Type in the name of the folder and recipe! &6example your_recipe"
      invalid_recipe: "This recipe is not a %RECIPE_TYPE%!"
items:
  none:
    glass_gray:
      name: '&4'
    glass_red:
      name: '&4'
    glass_green:
      name: '&4'
    glass_white:
      name: '&4'
    minimize:
      name: '&3Minimize'
      help: []
    back:
      name: '&5Back'
      help: []
    close:
      name: '&4Close'
      help: []
    gui_help:
      name: '&2Help'
      lore:
        - "&7-Click Me-"
      help: []
  main_menu:
    craft_recipe:
      name: "&6Workbench Recipe"
      help:
        - ""
    furnace_recipe:
      name: "&6Furnace Recipe"
      help:
        - ""
    item_editor:
      name: '&6Item Creator'
      help:
        - '&7Create, Save custom Items'
        - '&6Use them inside of your recipes'
    create_recipe:
      name: '&6Create Recipe'
      help:
        - '&7Create your own recipe'
    edit_recipe:
      name: '&7Edit Recipe'
      help:
        - '&7Edit a existing recipe'
    delete_recipe:
      name: '&4Delete Recipe'
      help:
        - '&7Delete a existing recipe'
    recipe_list:
      name: "&2Recipe List"
      help:
        - "&7List of recipes"
        - "&6Toggle Recipes on/off"
  item_editor:
    load_item:
      name: "&6Load"
      help:
        - "&7Load a existing Item"
    create_item:
      name: "&6Create"
      help:
        - "&7Create a custom Item"
    edit_item:
      name: "&7Edit"
      help:
        - "&7Edit a existing Item"
    delete_item:
      name: "&4Delete"
      help:
        - "&7Delete a custom Item"
  item_creator:
    item_name:
      name: '&6Change name'
      help:
        - "&7Edit Display Name"
    item_enchantments:
      name: '&6Enchantments'
      help:
        - "&7Edit Enchantments"
    item_lore:
      name: '&6Edit Lore'
      help:
        - "&7Add or Remove Lore lines"
    item_flags:
      name: '&6Set Flags'
      help:
        - "&7Set HIDE Flags"
        - "&7e.g. Hide Enchants"
    skull_setting:
      name: '&6Skull Settings'
      help:
        - "&7Add Textures to Player Heads"
    attributes_modifiers:
      name: '&6Set Attributes'
      help:
        - "&7Add or remove Attribute Modifiers"
    unbreakable_on:
      name: '&aUnbreakable'
      help:
        - "&7Toggle Unbreakable"
    unbreakable_off:
      name: '&cBreakable'
      help:
        - "&7Toggle Unbreakable"
    save_item:
      name: '&aSave Item'
      help:
        - "&7Save the item to File"
        - "&7input: &3<folder> <file_name>"
    apply_item:
      name: "&aApply Item"
      help:
        - "Applies the Item to the recipe"
    set_displayname:
      name: "&6Set Display Name"
      help:
        - "&7Change Display Name"
    remove_displayname:
      name: "&3Remove Display Name"
      help:
        - "&7Removes Display Name and"
        - "&7reset it to default"
    skull_texture:
      name: "&6Apply Texture"
      help:
        - "&7Applies the texture of the Player Head"
        - "<- Input"
    skull_owner:
      name: "&6Set Skull Owner"
      help:
        - "&7Sets the Skull Owner"
        - "&7Input: &3<UUID or Player Name>"
    potion_effects:
      name: "&6Potion Effects"
      help:
        - "&7Configure Potion Effects"
    variants:
      name: "&6Variants"
      help:
        - "&7Sets the variants of ingredients"
        - "&7[&cWork in Progress&7]"
    up:
      name: "&7Page Up"
      help: []
    down:
      name: "&7Page Down"
      help: []
    potion_add:
      name: "&3Add Potion Effect"
      help: []
    potion_remove:
      name: "&4Remove Potion Effect"
      help: []
    enchant_add:
      name: '&6Add Enchantment'
      help: []
    enchant_remove:
      name: '&4Remove Enchantment'
      help: []
    lore_add:
      name: '&6Add Lore'
      help: []
    lore_remove:
      name: "&4Remove Lore"
      help: []
    variant_add:
      name: "&3Add Variant"
      help: []
    variant_remove:
      name: "&4Remove Variant"
      help: []
    flag_enchants:
      name: '%C%Hide Enchants'
      help: []
    flag_attributes:
      name: '%C%Hide Attributes'
      help: []
    flag_unbreakable:
      name: '%C%Hide Unbreakable'
      help: []
    flag_destroys:
      name: '%C%Hide Destroys'
      help: []
    flag_placed_on:
      name: '%C%Hide Placed On'
      help: []
    flag_potion_effects:
      name: '%C%Hide Potions'
      help: []
    attribute:
      generic_max_health:
        name: '&6GENERIC_MAX_HEALTH'
        help: []
      generic_follow_range:
        name: '&6GENERIC_FOLLOW_RANGE'
        help: []
      generic_knockback_resistance:
        name: '&6GENERIC_KNOCKBACK_RESISTANCE'
        help: []
      generic_movement_speed:
        name: '&6GENERIC_MOVEMENT_SPEED'
        help: []
      generic_flying_speed:
        name: '&6GENERIC_FLYING_SPEED'
        help: []
      generic_attack_damage:
        name: '&6GENERIC_ATTACK_DAMAGE'
        help: []
      generic_attack_speed:
        name: '&6GENERIC_ATTACK_SPEED'
        help: []
      generic_armor:
        name: '&6GENERIC_ARMOR'
        help: []
      generic_armor_toughness:
        name: '&6GENERIC_ARMOR_TOUGHNESS'
        help: []
      generic_luck:
        name: '&6GENERIC_LUCK'
        help: []
      horse_jump_strength:
        name: '&6HORSE_JUMP_STRENGTH'
        help: []
      zombie_spawn_reinforcements:
        name: '&6ZOMBIE_SPAWN_REINFORCEMENTS'
        help: []
      add_number:
        name: '%C%Add number'
        help: []
      add_scalar:
        name: '%C%Multiply number'
        help: []
      multiply_scalar_1:
        name: '%C%Add percentage'
        help: []
      slot_hand:
        name: '&6Hand'
        help: []
      slot_off_hand:
        name: '&6Off_Hand'
        help: []
      slot_feet:
        name: '&6Feet'
        help: []
      slot_legs:
        name: '&6Legs'
        help: []
      slot_chest:
        name: '&6Chest'
        help: []
      slot_head:
        name: '&6Head'
        help: []
      save:
        name: '&aAdd Attribute'
        help: []
      delete:
        name: '&cRemove Attribute'
        help: []
      set_amount:
        name: '&aAmount: &6%NUMBER%'
        help: []
      set_name:
        name: "&3Name:&7 %NAME%"
        help: []
      set_uuid:
        name: "&3UUID:&7 %UUID%"
        help: []
  recipe_editor:
  recipe_creator:
    save:
      name: "&3Save"
      help: []
    permissions_on:
      name: "&3Permissions"
      help: []
    permissions_off:
      name: "&4No Permissions"
      help: []
    extends:
      name: "&3Extends: %EXT%"
      help:
        - "&7Sets the recipe this recipe extends of"
        - "&7Input: &3<namespace> <recipe_name>"
    workbench:
      adv_workbench_on:
        name: "&3Advanced Workbench"
        help:
          - "&7Can only be crafted in"
          - "&7Advanced Workbenches"
          - ""
      adv_workbench_off:
        name: "&4Every Workbench"
        help:
          - "&7Can be crafted in every Workbench"
      shapeless_off:
        name: '&3Shaped Recipe'
        help:
          - '&7Recipe has a shape!'
      shapeless_on:
        name: '&3Shapeless Recipe'
        help:
          - '&7Recipe is shapeless!'
    furnace:
      adv_furnace_on:
        name: "&3Advanced Furnace"
        help: []
      adv_furnace_off:
        name: "&4Every Furnace"
      xp:
        name: "&3Experience"
        help: []
        lore:
          - "&6%XP% Exp"
      cooking_time:
        name: "&6Cooking Time"
        help:
          - "&7Set the time how long the item"
          - "&7needs to cook in ticks"
          - "&3Tip: 20ticks = 1sec"
        lore:
          - "&6%TIME% ticks"
  recipe_list:
    lores:
      disabled: "&7&l[&c&lDISABLED&7&l]"
      enabled: "&7&l[&c&lDISABLED&7&l]"
    previous_page:
      name: "&2Previous Page"
      help: []
    next_page:
      name: "&2Next Page"
      help: []

inventories:
  main_menu: '&3&lCustomCrafting'
  item_editor: "&0&lItem Editor"
  item_creator: "&0&lItem Creator"
  recipe_editor: "&4&lRecipe Editor"
  recipe_creator: "&4&lRecipe Creator"
  recipe_list: "&8&lRecipe List"
