# Language: en_US

translated_by: 'WolfyScript yt: https://www.youtube.com/channel/UCTlqRLm4PxZuAI4nVN4X74g'
# ######################################################################################################
loading-languages: '&3Loading languages...'
loading-recipes: '&3Loading recipes.....'
loading-recipe-file: 'Loading recipe out of&6 %FILE% ...'
loading-recipe-successful: 'Successfully loaded recipe&6 %RECIPE%'
loading-complete: '                &3Everything successfully loaded!'
# ######################################################################################################
error-workbench-material: 'Cause: can''t get Material: %MATERIAL%'
error-workbench: 'ERROR loading Workbench crafting recipe!'
error-recipe-material: 'Cause: can''t get Material: %MATERIAL%'
error-recipe-output: 'Cause: can''t load output item!'
error-recipe: 'ERROR loading Custom recipe: %RECIPE%'
# ######################################################################################################
config-example-api: 'This number is for the future, when the config settings change!
                      Then there will be a Converter which will migrate the old configs to the new version!'
config-example-permission: 'Here you can set if the players need to have permission
                             in order to use the recipe! The permission is build as follows -> customcrafting.craft.<recipe_ID>'
config-example-workbench: 'You can also set if the recipe can be crafted in the normal
  workbench! If want so, set it to false and then it can be crafted in the normal
  workbench!'
config-example-enchantments: 'Every enchantment > Name_ID:Level < The Enchantment_IDs
  can be found here -> https://minecraft.gamepedia.com/Java_Edition_data_values#Enchantment_IDs'
config-example-materials-0: 'Use the name_ID from minecraft or use the Spigot Materials
  names'
config-example-materials-1: 'When Shapeless recipe add materials with any key you want!'
config-main-debug: 'Just for testing purpose'



items:
  none:
    glass_gray:
      name: '&4'
    glass_red:
      name: '&4'
    minimize:
      name: '&3Minimize'
      help: []
    back:
      name: '&5Back'
      help: []
    close:
      name: '&4Close'
      help: []
    gui_help:
      name: '&2Help'
      lore:
        - "Help"
      help: []

  main_menu:
    craft_recipe:
      name: "&6Workbench Recipe"
      help:
        - ""
    furnace_recipe:
      name: "&6Furnace Recipe"
      help:
        - ""
    item_creator:
      name: '&6Item Creator'
      help:
        - '&7Create items and save them'
        - '&6They can be used in recipes'

    create_recipe:
      name: '&6Create Recipe'
      help:
        - '&7Create your own recipe'
    edit_recipe:
      name: '&7Edit Recipe'
      help:
        - '&7Edit a existing recipe'
    delete_recipe:
      name: '&4Delete Recipe'
      help:
        - '&7Delete a existing recipe'
    recipe_list:
      name: "&2Recipe List"
      help: []
  recipe_mainmenu:
  item_mainmenu:
    item_name:
      name: '&6Change name'
      help: []
    item_enchantments:
      name: '&6Enchantments'
      help: []
    item_lore:
      name: '&6Edit Lore'
      help: []
    item_flags:
      name: '&6Set Flags'
      help: []
    skull_owner:
      name: '&6Set skull owner'
      help: []
    skull_texture:
      name: '&6Set skull texture'
      help: []
    attributes_modifiers:
      name: '&6Set Attributes'
      help: []
    unbreakable_on:
      name: '&aUnbreakable'
      help: []
    unbreakable_off:
      name: '&cBreakable'
      help: []
    item_advanced:
      name: '&6Options for grid'
      help: []
    save_item:
      help: []
      name: '&aSave item'
  furnace_mainmenu:

  craft_editor_main:
    save:
      name: "&3Save"
      help: []
    permissions:
      name: "%C%Permissions"
      help: []
    adv_workbench:
      name: "%C%Advanced Workbench"
      help: []
  craft_editor_result:
  craft_editor_ingredient:

  recipes_mainmenu:
    grid_options:
      name: '&8Grid Settings'
      help:
        - '&7Set the recipe dimensions'
        - '&7Create &62x2&7, &61x3&7, etc. recipes'
    grid_options_off:
      name: '&8&mGrid Settings'
      help:
        - '&7This option is disabled!'
        - '&6Set to shaped recipe to use this option!'
    shapeless_wrong:
      name: '&3Shaped Recipe'
      help:
        - '&7Recipe has a shape!'
    shapeless_right:
      name: '&3Shapeless Recipe'
      help:
        - '&7Recipe is shapeless!'
    recipe_save:
      name: '&2Save Recipe'
      help:
        - '&7Save current recipe'
    permission_true:
      name: '&aNeeds Permission'
      help:
        - '&7Players need permission to craft'
    permission_false:
      name: '&cNo Permission'
      help:
        - '&7No permissions needed'
    workbench_true:
      name: '&aNeeds Advanced Workbench'
      help:
        - '&7Recipe can only be crafted'
        - '&7in a advanced workbench!'
    workbench_false:
      name: '&cNo Advanced Workbench'
      help:
        - '&7Recipe can be crafted everywhere!'
  recipes_slot_options:
    item_name:
      name: '&6Change name'
      help: []
    item_lore:
      name: '&6Edit Lore'
      help: []
    item_flags:
      name: '&6Set Flags'
      help:
        - '&7Configure the flags to hide attributes:'
        - '&7Hide &6enchants&7,&6 unbreakable&7,&6 etc.'
    item_enchantments:
      name: '&6Enchantments'
      help:
        - '&7Set the enchants of the item'
    item_advanced:
      name: '&6Advanced options'
      help:
        - '&7More detailed options!'
        - 'e.g. variant items, skull textures'
  delete_menu:
    delete_right:
      name: '&aYes'
      help: []
    delete_wrong:
      name: '&4No'
      help: []
    recipe_name:
      name: '%RECIPE_NAME%'
      help:
        - '- The recipe name! -'
  recipes_item_list:
    last_page:
      name: '&5Last page'
      help: []
    next_page:
      name: '&5Next page'
      help: []
    remove_:
      name: '&4Remove %ITEM_ID%'
      help: []
  recipes_grid_options:
    grid_times:
      name: '&3'
      help: []
    grid_height_1:
      name: '&3Height 1'
      help: []
    grid_height_2:
      name: '&3Height 2'
      help: []
    grid_height_3:
      name: '&3Height 3'
      help: []
    grid_width_1:
      name: '&3Width 1'
      help: []
    grid_width_2:
      name: '&3Width 2'
      help: []
    grid_width_3:
      name: '&3Width 3'
      help: []
  recipes_advanced_slot_options:
    display_names_list:
      name: '&aAllowed display names'
      help: []
    display_name_add:
      name: '&6Add name'
      help: []
    display_name_remove:
      name: '&6Remove name'
      help: []
    display_name_on_true:
      name: '&2Display name | enabled'
      help: []
    display_name_on_false:
      name: '&4Display name | disabled'
      help: []
    skull_owners_list:
      name: '&aAllowed skull owners'
      help: []
    skull_owner_add:
      name: '&6Add owner'
      help: []
    skull_owner_remove:
      name: '&6Remove owner'
      help: []
    skull_textures_list:
      name: '&aAllowed skull textures'
      help: []
    skull_texture_add:
      name: '&6Add texture'
      help: []
    skull_texture_remove:
      name: '&6Remove texture'
      help: []
    lore_list:
      name: '&aAllowed lore'
      help: []
    lore_add:
      name: '&6Add lore'
      help: []
    lore_remove:
      name: '&6Remove lore'
      help: []
    enchants_list:
      name: '&aAllowed enchants'
      help: []
    enchant_add:
      name: '&6Add enchantment'
      help: []
    enchant_remove:
      name: '&6Remove enchantment'
      help: []
    variant_items_list:
      name: '&aAllowed variants'
      help: []
    variant_item_add:
      name: '&6Add variant'
      help: []
    variant_item_remove:
      name: '&6Remove variant'
      help: []
  add_skull_texture:
    use_chat:
      name: '&6Type URL in Chat'
      help: []
  result_options:
    item_name:
      name: '&6Change name'
      help: []
    item_enchantments:
      name: '&6Enchantments'
      help: []
    item_lore:
      name: '&6Edit Lore'
      help: []
    item_flags:
      name: '&6Set Flags'
      help: []
    skull_owner:
      name: '&6Set skull owner'
      help: []
    skull_texture:
      name: '&6Set skull texture'
      help: []
    attributes_modifiers:
      name: '&6Set Attributes'
      help: []
    unbreakable_on:
      name: '&aUnbreakable'
      help: []
    unbreakable_off:
      name: '&cBreakable'
      help: []
    item_file:
      name: '&6Set Item File'
      help: []

  item_advanced_options:
    'null':
      name: NONE
  enchant_options:
    enchantment_add:
      name: '&6Add Enchantment'
      help: []
    enchantment_remove:
      name: '&4Remove Enchantment'
      help: []
  lore_options:
    remove_lore:
      name: '&4Remove Lore'
      help: []
    add_lore:
      name: '&6Add Lore'
      help: []
  flags_options:
    flag_enchants:
      name: '&4Hide Enchants'
      help: []
    flag_enchants_true:
      name: '&2Enabled'
      help: []
    flag_enchants_false:
      name: '&4Disabled'
      help: []
    flag_attributes:
      name: '&4Hide Attributes'
      help: []
    flag_attributes_true:
      name: '&2Enabled'
      help: []
    flag_attributes_false:
      name: '&4Disabled'
      help: []
    flag_unbreakable:
      name: '&4Hide Unbreakable'
      help: []
    flag_unbreakable_true:
      name: '&2Enabled'
      help: []
    flag_unbreakable_false:
      name: '&4Disabled'
      help: []
    flag_destroys:
      name: '&4Hide Destroys'
      help: []
    flag_destroys_true:
      name: '&2Enabled'
      help: []
    flag_destroys_false:
      name: '&4Disabled'
      help: []
    flag_placed_on:
      name: '&4Hide Placed On'
      help: []
    flag_placed_on_true:
      name: '&2Enabled'
      help: []
    flag_placed_on_false:
      name: '&4Disabled'
      help: []
    flag_potion_effects:
      name: '&4Hide Potions'
      help: []
    flag_potion_effects_true:
      name: '&2Enabled'
      help: []
    flag_potion_effects_false:
      name: '&4Disabled'
      help: []
  attribute_options:
    attribute_max_health:
      name: '&6GENERIC_MAX_HEALTH'
      help: []
    attribute_follow_range:
      name: '&6GENERIC_FOLLOW_RANGE'
      help: []
    attribute_knockback_resistance:
      name: '&6GENERIC_KNOCKBACK_RESISTANCE'
      help: []
    attribute_movement_speed:
      name: '&6GENERIC_MOVEMENT_SPEED'
      help: []
    attribute_flying_speed:
      name: '&6GENERIC_FLYING_SPEED'
      help: []
    attribute_attack_damage:
      name: '&6GENERIC_ATTACK_DAMAGE'
      help: []
    attribute_attack_speed:
      name: '&6GENERIC_ATTACK_SPEED'
      help: []
    attribute_armor:
      name: '&6GENERIC_ARMOR'
      help: []
    attribute_armor_toughness:
      name: '&6GENERIC_ARMOR_TOUGHNESS'
      help: []
    attribute_luck:
      name: '&6GENERIC_LUCK'
      help: []
    attribute_horse_jump_strength:
      name: '&6HORSE_JUMP_STRENGTH'
      help: []
    attribute_zombie_spawn_reinforcements:
      name: '&6ZOMBIE_SPAWN_REINFORCEMENTS'
      help: []
  attribute_values:
    operation_add_number:
      name: '%C%Add number'
      help: []
    operation_add_scalar:
      name: '%C%Multiply number'
      help: []
    operation_multiply_scalar_1:
      name: '%C%Add percentage'
      help: []
    slot_hand:
      name: '&6Hand'
      help: []
    slot_off_hand:
      name: '&6Off_Hand'
      help: []
    slot_feet:
      name: '&6Feet'
      help: []
    slot_legs:
      name: '&6Legs'
      help: []
    slot_chest:
      name: '&6Chest'
      help: []
    slot_head:
      name: '&6Head'
      help: []
    attribute_save:
      name: '&aAdd Attribute'
      help: []
    attribute_delete:
      name: '&cRemove Attribute'
      help: []
    set_amount:
      name: '&aAmount: &6%NUMBER%'
      help: []

inventories:
  main_menu: '&6CustomCrafting'
  item_mainmenu: "&2Item Creator"
  recipe_mainmenu: "&2Recipe Creator"
  furnace_mainmenu: "&2Furnace Recipe Creator"
  craft_editor_main: "&6Workbench Recipe Editor"
  craft_editor_ingredient: "&6"

  editor_result: "&6Edit Result"
  recipe_list: "&6Recipe List"















